# Setup TensorFlow

In [ ]:
# Install TensorFlow if needed
!pip install tensorflow --quiet

# Import TensorFlow
import tensorflow as tf

# Check TensorFlow version
print("TensorFlow Version:", tf.__version__)

TensorFlow Version: 2.18.0


# Basics: Creating Tensors
## Scalar

In [ ]:
# Scalar (Rank-0)
scalar = tf.constant(42)
print("Scalar:", scalar.numpy())



Scalar: 42


## Vector

In [ ]:
# Vector (Rank-1)
vector = tf.constant([1, 2, 3])
print("Vector:", vector.numpy())



Vector: [1 2 3]


## Matrix

In [ ]:
# Matrix (Rank-2)
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
print("Matrix:\n", matrix.numpy())



Matrix:
 [[1 2 3]
 [4 5 6]]


In [ ]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


## 3D Tensor

In [ ]:
# 3D Tensor (Rank-3)
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Tensor:\n", tensor_3d.numpy())


3D Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# There can be an arbitrary number of axes ("dimensions")
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


## Convert Tensor to NumPy Array

In [ ]:
# Convert tensor to NumPy array
numpy_array = matrix.numpy()
print("NumPy Array:\n", numpy_array)

NumPy Array:
 [[1 2 3]
 [4 5 6]]


# Basic Math Operations

## Addition

In [ ]:
a = tf.constant([2, 3])
b = tf.constant([4, 5])

# Addition
add_result = a + b
print("Addition:", add_result.numpy())

Addition: [6 8]


## Element-wise Multiplication

In [ ]:
a = tf.constant([2, 3])
b = tf.constant([4, 5])

# Element-wise Multiplication
mul_result = a * b
print("Element-wise Multiplication:", mul_result.numpy())



Element-wise Multiplication: [ 8 15]


## Matrix Multiplication

In [ ]:
# Matrix Multiplication
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])

matmul_result = tf.matmul(A, B)
print("Matrix Multiplication:\n", matmul_result.numpy())

Matrix Multiplication:
 [[19 22]
 [43 50]]


# Math Functions

In [ ]:
# Create a sample tensor with float32 data type
tensor = tf.constant([[3, 7, 1], [10, 5, 8]], dtype=tf.float32)

# Max value in the tensor
max_value = tf.reduce_max(tensor)
print("Max Value:", max_value.numpy())




Max Value: 10.0


In [ ]:
# Index of max values (argmax)
argmax_value = tf.argmax(tensor, axis=1)  # Find max indices along axis-1 (rows)
print("Argmax (Max indices per row):", argmax_value.numpy())



Argmax (Max indices per row): [1 0]


In [ ]:
# Softmax function (for probability distribution)
softmax_result = tf.nn.softmax(tensor)
print("Softmax Result:\n", softmax_result.numpy())

Softmax Result:
 [[0.01794253 0.9796292  0.00242826]
 [0.8756006  0.00589975 0.11849965]]


# Tensor Indexing

## Single-Axis Indexing


In [ ]:
tensor = tf.constant([10, 20, 30, 40, 50])

# Access elements
print("First Element:", tensor[0].numpy())
print("Last Element:", tensor[-1].numpy())

First Element: 10
Last Element: 50


## Multi-Axis Indexing

In [ ]:
# 2D Tensor
matrix = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access elements
print("Element at (0,1):", matrix[0, 1].numpy())  # Row 0, Column 1
print("First row:", matrix[0].numpy())  # Entire first row
print("First column:", matrix[:, 0].numpy())  # Entire first column

Element at (0,1): 2
First row: [1 2 3]
First column: [1 4 7]


# Manipulating Shapes

In [ ]:
# Create tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])

# Reshape
reshaped_tensor = tf.reshape(tensor, (3, 2))
print("Reshaped Tensor:\n", reshaped_tensor.numpy())

# Expand Dimensions
expanded_tensor = tf.expand_dims(tensor, axis=0)
print("Expanded Tensor Shape:", expanded_tensor.shape)

# Squeeze (Remove dimensions of size 1)
squeezed_tensor = tf.squeeze(expanded_tensor)
print("Squeezed Tensor Shape:", squeezed_tensor.shape)


Reshaped Tensor:
 [[1 2]
 [3 4]
 [5 6]]
Expanded Tensor Shape: (1, 2, 3)
Squeezed Tensor Shape: (2, 3)


# DTypes in TensorFlow

In [ ]:
# Different Data Types
int_tensor = tf.constant([1, 2, 3], dtype=tf.int32)
float_tensor = tf.constant([1.1, 2.2, 3.3], dtype=tf.float32)

# Convert Data Type
converted_tensor = tf.cast(int_tensor, dtype=tf.float32)
print("Converted Tensor DType:", converted_tensor.dtype)


Converted Tensor DType: <dtype: 'float32'>


# Broadcasting

In [ ]:
# Create tensors of different shapes
A = tf.constant([[1, 2, 3], [4, 5, 6]])
B = tf.constant([[1], [2]])  # Shape (2,1)

# Broadcasted Addition
result = A + B
print("Broadcasted Result:\n", result.numpy())


Broadcasted Result:
 [[2 3 4]
 [6 7 8]]


# Convert NumPy to Tensor

In [ ]:
import numpy as np # import numpy and give it the alias 'np'

# Convert NumPy array to Tensor
numpy_array = np.array([10, 20, 30])
tensor = tf.convert_to_tensor(numpy_array)
print("Converted Tensor:", tensor.numpy())

Converted Tensor: [10 20 30]


# Ragged Tensor

In [ ]:
# Create a Ragged Tensor
ragged_tensor = tf.ragged.constant([[1, 2, 3], [4, 5], [6]])
print("Ragged Tensor:\n", ragged_tensor)


Ragged Tensor:
 <tf.RaggedTensor [[1, 2, 3], [4, 5], [6]]>


# String Tensor

In [ ]:
# String Tensor
string_tensor = tf.constant(["Hello", "TensorFlow", "World"])

# String operations
joined_string = tf.strings.join(["Hello", " ", "World"])
print("Joined String:", joined_string.numpy().decode('utf-8'))


Joined String: Hello World


# Sparse Tensor

In [ ]:
# Create a Sparse Tensor
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])

# Convert to Dense Tensor
dense_tensor = tf.sparse.to_dense(sparse_tensor)
print("Sparse Tensor:\n", sparse_tensor)
print("Dense Tensor:\n", dense_tensor.numpy())


Sparse Tensor:
 SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
Dense Tensor:
 [[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]]


Summary:

*  Shapes:	tensor.shape

*  Indexing:	tensor[row, col]

*  Math Operations:	+, *, tf.matmul()

*  Math Functions:	tf.reduce_max(), tf.argmax(), tf.nn.softmax()

*  Manipulating Shapes:	tf.reshape(), tf.expand_dims(), tf.squeeze()

*  DTypes:	tf.cast()

*  Broadcasting	Arithmetic on different shapes

* Convert to Tensor	tf.convert_to_tensor()
* Ragged Tensors:	tf.ragged.constant()
* String Tensors:	tf.strings.join()
* Sparse Tensors:	tf.sparse.SparseTensor(), tf.sparse.to_dense()